### ISSUE TITLE
Add permanently undefined characters (noncharacters)

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#108]
And see if that allows aligning some HTML and URL text to use a shared primitive and become more clear at the same time.

**Comment by annevk** [comment]
(Per https://github.com/whatwg/html/pull/2471.)

**Comment by domenic** [comment]
With the definition HTML uses, i.e.

> The control characters are those whose Unicode "General_Category" property has the value "Cc" in the Unicode UnicodeData.txt data file. [UNICODE]

? SGTM, assuming "Cc" stands for "control character". https://en.wikipedia.org/wiki/Control_character is also interesting.

**Comment by annevk** [comment]
Yeah, although I think I'd list the explicit ranges instead as we do elsewhere. (We could maybe flip that around for some of the others too and have the explicit ranges in notes instead...)

**Comment by domenic** [comment]
Hmm interesting. I generally like the idea of delegating to Unicode but for controls it probably doesn't matter as they really shouldn't add any more of those. For whitespace though I think they recently added a new whitespace, causing the ES spec to update in interesting ways. Food for thought.

**Comment by annevk** [comment]
This was fixed by ad1b87aecce01759096fcdbf6acc2bd6096c3168 from #114.
