### ISSUE TITLE
Edge case: a byte or code point that is a parenthesis

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#109]
URL has the latter. I guess we simply go with the formal name and not render it?

**Comment by domenic** [comment]
Hah, fun question. Yeah, I guess the formal name makes sense.

**Comment by zcorpan** [comment]
I could live with (() and ()) but maybe editors complain about unmatched parens?

HTML currently has "U+0028 LEFT PARENTHESIS (()" in srcset parser btw.
