### ISSUE TITLE
Incorrect definition of `ASCII upper hex digit` and `ASCII lower hex digit`. 

### ISSUE THREAD

**Issue by inikulin** [whatwg/infra#122]
Currently `ASCII upper hex digit` and `ASCII lower hex digit` are defined as:
> An ASCII upper hex digit is an ASCII digit or a code point in the range U+0041 (A) to U+0046 (F), inclusive.
> An ASCII lower hex digit is an ASCII digit or a code point in the range U+0061 (a) to U+0066 (f), inclusive.

These definitions render [hexademical character consumption in parser](https://html.spec.whatwg.org/multipage/syntax.html#hexademical-character-reference-state) incorrect:
consumption algorithm should distinguish `ASCII upper hex digit`, `ASCII lower hex digit` and `ASCII digit`.

 However, with current definition `ASCII digit` is a subset of two first. Moreover, it's not quite semantically correct that `lower hex digit` or `upper hex digit` include `ASCII digit`. 

I can issue a PR, although I'm not sure about other usages of terms in specs. It would be nice if someone competent  review all these usages and determine which definition is implied in each case.

**Comment by annevk** [comment]
I think this is more a bug in that section of the parser. Note that HTML always defined these ranges in that way: https://github.com/whatwg/html/commit/104bd78697738af2eab61740a2f1421ae49a3c95.

**Comment by domenic** [comment]
I'm confused. Switches go from top to bottom, so I don't see the issue.

**Comment by domenic** [comment]
Oh wait, I see it :(

**Comment by annevk** [comment]
@domenic if we reorder them it would be okay I suppose.

This might have been introduced in https://github.com/whatwg/html/commit/6c629ac9e5736cdb824293999673de6a0f5ea06d, but it's definitely not a problem with Infra.

**Comment by annevk** [comment]
I wonder if @RReverser and @zcorpan used this definition elsewhere too thinking it had a different range.

**Comment by annevk** [comment]
Never mind, there's only two usage instances in HTML. I'll post a fix.

**Comment by RReverser** [comment]
@inikulin Nice catch! One more broken thing to the personal list... (Although, technically, it wasn't a regression, rather incorrect definition from scratch as previously there was no formal definition at all.)
