### ISSUE TITLE
Record-like data structure

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#13]
I'd like URL record, request, and response to just be some data structure so you can more easily address their members.

They're basically maps with fixed keys or what JavaScript calls records. The values are mostly mutable still, but thus far they don't have things similar to methods.

**Comment by domenic** [comment]
My tentative comment on this idea is at https://github.com/whatwg/infra/issues/21#issuecomment-260380736

**Comment by annevk** [comment]
So a request and a response become a very large tuple? I guess that's reasonable.

**Comment by domenic** [comment]
Hmm yeah, the internal versions at least. It's interesting how Web IDL objects get a bunch of associated fields, but purely spec objects become tuples. I guess that's working as intended though.

**Comment by tobie** [comment]
Why not use maps for this?

**Comment by annevk** [comment]
@tobie we don't want mutations in size.

**Comment by annevk** [comment]
A problem with using tuples though is that the order being defined can be a big problem for changing the API shape over time. If folks start passing a request around as a literal, then it would be very hard to add additional fields (except at the end, but that's not always the best place).
