### ISSUE TITLE
Undeclared token in "split a string input on ASCII whitespace"

### ISSUE THREAD

**Issue by triple-underscore** [whatwg/infra#131]
https://infra.spec.whatwg.org/commit-snapshots/aa54c3607830989882e964938695d67ec2b6703d/

The step 4 in  “To split a string input on ASCII whitespace“
( https://infra.spec.whatwg.org/#split-on-ascii-whitespace ):

> Append token to tokens.

This variable token has no value set.
Seems this step is unnecessary.

**Comment by domenic** [comment]
I think there might be a missing step instead, but we should try to find the original algorithm and confirm.

**Comment by annevk** [comment]
This was introduced in #48. Looking at what got removed at https://github.com/whatwg/html/commit/104bd78697738af2eab61740a2f1421ae49a3c95#diff-36cd38f49b9afa08222c0dc9ebfe35ebL6447 it seems that @triple-underscore is right and that the step got added in error somehow when converting to "modern" style algorithms.
