### ISSUE TITLE
RFC 2119 keywords in lowercase

### ISSUE THREAD

**Issue by domenic** [whatwg/infra#133]
https://infra.spec.whatwg.org/commit-snapshots/1d4c71382a524b9659e383a1dadbf97d871f52da/#conformance

> These keywords have equivalent meaning when written in lowercase

Apparently this is not allowed by https://tools.ietf.org/html/rfc8174. We should explicitly state that we, and other documents that use Infra, are willfully violating RFC 8174. We should perhaps move the definition of "willful violation" from HTML to Infra as well.

**Comment by annevk** [comment]
We could also dfn "must", "must not", "should", and "may" and just state they mean "MUST", "MUST NOT", "SHOULD", and "MAY". Which technically means we don't violate it other than in spirit. Probably better to be upfront about it though.

**Comment by sideshowbarker** [comment]
Maybe this point isn’t relevant, but I notice that https://tools.ietf.org/html/rfc8174 explicitly says *in IETF documents*:

> This document defines how those words are interpreted **in IETF documents** when the words are in all capitals.

In other words, it doesn’t normatively restrict how keywords are formatted in non-IETF documents.

**Comment by domenic** [comment]
Yeah, it's a bit weird, but I think since we're already encouraging use of RFC 2119 in non-IETF documents, we should probably treat our encouragement of violating RFC 8174 as a willful violation.
