### ISSUE TITLE
"contains an entry with a given key" (and similar) should use base word in `lt`

### ISSUE THREAD

**Issue by tabatkins** [whatwg/infra#135]
https://infra.spec.whatwg.org/commit-snapshots/e88a63efc4663eedc6cb3081002c26935014c25d/#map-exists

> contains an entry with a given key

The above definition (for map and others) has an `lt="exists | contains"`. This interfere's with Bikeshed's ability to conjugate the words when autolinking; for example, it can't match this with a "containing" autolink.  Both of these words should be in their base form: `lt="exist | contain"`.

**Comment by annevk** [comment]
I think we might not have done that here because we didn't consider usage of them as "exist" or "contain" correct. Not sure though.

**Comment by domenic** [comment]
Nah, we should fix this. Consider "After this step, x will contain y" or similar.

**Comment by tabatkins** [comment]
Precisely that.  "contain" vs "contains" isn't a semantic distinction; you swap between them just based on the plurality of the subject! In particular, I'm saying things like "if the 'foo' or 'bar' keys exist in the map".

But also, as I said, Bikeshed can't conjugate "contains" into "contained" or "containing".  (It can conjugate "contains" into "contain", but it doesn't do any two-step conjugations, both for cost reasons and to avoid accidentally matching too many things unwantedly.)
