### ISSUE TITLE
Should we allow variable shadowing?

### ISSUE THREAD

**Issue by domenic** [whatwg/infra#141]
Currently we say variables are block scoped, implying the following is OK:

1. Let _x_ be "foo"
1. If _y_ is "bar", then
   1. Let _x_ be 5
   2. Print _x_
1. Print _x_

and that it will print 5, then "foo".

Should we just say that you're not supposed to declare the same variable multiple times per algorithm, i.e. you cannot "shadow" variable names? Or we could discourage it, without prohibiting it?

**Comment by GPHemsley** [comment]
I'd say discourage it without outright prohibiting it (though I can't think of a usecase that would require it).

**Comment by annevk** [comment]
I'd be okay with prohibiting since it seems super confusing (and doesn't translate well across languages).

**Comment by tobie** [comment]
Yeah that generally sounds like a bad idea. It's really easy to miss an accidentally removed `Let` clause, in such cases, as the the algorithm still looks correct. Compare:

1. Let x be "foo"
1. If y is "bar", then
    1. Let x be y;
    1. Print x
1. Do stuff.

vs:

1. Let x be "foo"
1. If y is "bar", then
    1. Print x
1. Do stuff.
