### ISSUE TITLE
[... What's so special about 0x28 and 0x29?]

### ISSUE THREAD

**Issue by SamB** [whatwg/infra#144]
https://infra.spec.whatwg.org/commit-snapshots/d28f5cde2bd2168f29b5fc8b26603f189132399a/#bytes

> An ASCII byte is a byte in the range 0x00 \(NUL\) to 0x7F \(DEL\), inclusive\. As illustrated, an ASCII byte, excluding 0x28 and 0x29, may be followed by the representation outlined in the Standard Code section of ASCII format for Network Interchange, between parentheses\. \[RFC20\]
> 
> 0x28 may be followed by "\(left parenthesis\)" and 0x29 by "\(right parenthesis\)"\. 

Hmm, a "(see next paragraph)" after "excluding 0x28 and 0x29" might save people from rushing off to see what's so special about those codepoints ;-).  Just maybe....

**Comment by domenic** [comment]
I'm really hoping that people can read more than one paragraph at a time before hitting the bug tracker, so I don't think this is necessary...

**Comment by annevk** [comment]
Agreed, I think this is clear enough.
