### ISSUE TITLE
Link asserts?

### ISSUE THREAD

**Issue by littledan** [whatwg/infra#163]
@domenic suggested that I link asserts to the infra spec. However, Bikeshed didn't generate pretty markup when I did this and the example here doesn't seem to do that either. What is the recommendation?

As a tangent: for specs I work on in JS, I frequently see misunderstanings, even among implementers, that asserts would throw an exception when run. The text here is pretty clear that that does not happen, but maybe it should be spelled out even more explicitly, specifically that there is no exception.

**Comment by domenic** [comment]
If you think this would be helpful we can definitely do it. I'll whip up a PR, unless @annevk disagrees. Then you'd do `[=Assert:=]` in Bikeshed (or maybe Bikeshed won't like colons and we'll have to do `[=Assert=]:`, we'll see).

**Comment by littledan** [comment]
I don't have much of opinion one way or another on linking, just trying to learn what the encouraged practice is here.

**Comment by annevk** [comment]
I'm fine with this; I'd prefer the variant where the colon is not part of the link.
