### ISSUE TITLE
Definition of propagating exceptions, ? and !

### ISSUE THREAD

**Issue by littledan** [whatwg/infra#164]
The JS spec uses ? when calling an abstract algorithm which might throw, and ! when calling an abstract algorithm and asserting that it won't throw. It seems like a lot of web specs are based around exceptions implicitly being propagated (as in JS), but other times, e.g., in some places in HTML, I see ? and ! explicitly as in JS. It would be good to clarify what is the best practice in this document. For example, should we use ? or ! whenever "calling into" JS, and never otherwise?

**Comment by domenic** [comment]
This is defined by https://infra.spec.whatwg.org/#algorithm-control-flow for places that don't use ES spec conventions.

**Comment by annevk** [comment]
If at some point we can harmonize both that'd be nice, but calling out that particular steps use ES conventions is probably good enough for the foreseeable future.
