### ISSUE TITLE
Define conditionals

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/infra#180]
Clarify the prose for conditionals, and perhaps what should be considered true/false.

**Comment by annevk** [comment]
Also that we use "If" and "Otherwise" (and not "Else"), unless we want to change that...

**Comment by domenic** [comment]
This feels a bit too prescriptive, and more in the realm of style guide than Infra. But if the people are asking for it, I'm not sure we should deny it to them... :)

**Comment by jakearchibald** [comment]
It's something that gets corrected in PRs, so it feels like it should be documented *somewhere*.

**Comment by annevk** [comment]
Once you have "Otherwise", "then" is no longer used. So it's:

1. If …, then ….
2. Otherwise, if …, ….
3. Otherwise, ….

This does seem somewhat worthwhile adding at this point.

**Comment by domenic** [comment]
> Once you have "Otherwise", "then" is no longer used.

I don't understand the logic behind this. It rubs my brain the wrong way to see "if ..., then ..." used in one line, and "if ..., ..." used on the next.

**Comment by annevk** [comment]
Often you wouldn't have "Otherwise, if ..., ..." as we do use early returns commonly, but as far as I can tell that's the convention we've been using for quite a while now. It also reads better I think.
