### ISSUE TITLE
String concenatation

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#185]
How about:

> To string concatenate a list _list_ with an optional separator _separator_, run these steps:
> 1. If _list_ is empty, then return the empty string.
> 2. Assert: _list_ only contains strings.
> 3. If _separator_ is not given, then set _separator_ to the empty string.
> 4. Assert: _separator_ is a string.
> 5. Return a string whose contents are _list_'s items, in order, separated from each other by _separator_.

Needed for https://github.com/whatwg/dom/issues/555 and HTML; possibly other places. (URL concatenates bytes as well, but we don't have generics so...)

cc @Ms2ger

**Comment by domenic** [comment]
I'd minorly prefer "a list of strings _list_ with an optional separator string _separator_" then remove the asserts.

I think you could also just define it as "concatenate" with for=string or similar.
