### ISSUE TITLE
Inclusive or and singular/plural verbs

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#190]
"If X or Y are present and are 0" or "If X or Y is present and is 0"?

Background: https://github.com/whatwg/html/pull/3408.

cc @junov

**Comment by domenic** [comment]
I don't think this is an Infra matter, but the second seems more correct; it seems be an extreme shortening of "If X or Y is present and [the one that is present] is 0".

The whole sentence is awkward though; better to break it into "If X is present and is 0, or Y is present and is 0".

**Comment by annevk** [comment]
Yeah, I guess it's more something for the style guide, but Infra does define we use "inclusive or".
