### ISSUE TITLE
Use PNGs for link rel=icon in WHATWG specs?

### ISSUE THREAD

**Issue by inexorabletash** [whatwg/infra#191]
_Filing this against Infra, since it applies to all specs..._

WHATWG specs have `<link href="https://resources.whatwg.org/logo-XXX.svg" rel="icon">`

[Browser support for SVG favicons is poor](https://caniuse.com/#feat=link-icon-svg) and [doesn't seem likely to improve soon](https://bugs.chromium.org/p/chromium/issues/detail?id=294179). Can these be switched to use the `.png` versions?

&lt;&lt;Insert argument about this being an incentive for browsers to prioritize supporting SVG favicons here.&gt;&gt;

(As an aside: kudos on the XHR logo. That makes me smile every time I see it.) 

cc: @foolip

**Comment by domenic** [comment]
The better place for issues in all specs is whatwg/meta :). Where we actually already have this issue: https://github.com/whatwg/meta/issues/10. So, let's move it there.

Personally I've just switched to Firefox ;).
