### ISSUE TITLE
Infra lacks a "JSON stringify and UTF-8 encode to bytes" operation

### ISSUE THREAD

**Issue by equalsJeffH** [whatwg/infra#193]
Infra features a [**parse JSON from bytes**](https://infra.spec.whatwg.org/#parse-json-from-bytes) operation, but lacks a "JSON stringify and UTF-8 encode to bytes" operation.

see also [webauthn](https://github.com/w3c/webauthn) issue [#712 JSON-serialized client data is wrong](https://github.com/w3c/webauthn/issues/712)

**Comment by annevk** [comment]
If someone wants to fix this, https://github.com/w3c/webauthn/issues/712#issuecomment-370094337 has instructions.

**Comment by jakearchibald** [comment]
Is it ok to call out to ECMAScript here? Wouldn't that fail in in-parallel steps?
