### ISSUE TITLE
For each x in/of y

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#194]
Currently we suggest "of", but there's a lot of text out there saying "in". Should we allow both, switch to "in", or change all the things to "of"?

**Comment by domenic** [comment]
Probably easiest to just allow "in"; I don't feel there's a lot of value in uniformity here?

**Comment by annevk** [comment]
Yeah, though it's also nice not to have to think about it and for specifications to be self-consistent. Currently they use different styles depending on who writes the PR or what mood they're in. 😊

**Comment by annevk** [comment]
I now think we should treat this as a bug and only allow "of".
