### ISSUE TITLE
Ternary revisited

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#247]
#175 added a ternary construct, but we don't use it consistently. Some examples:

> Let activationTarget be target, if isActivationEvent is true and target has activation behavior, and null otherwise.

> To pop from a stack is to remove its last item and return it, if the stack is not empty, or to return nothing otherwise.

I created a Twitter poll to help https://twitter.com/annevk/status/1123219698198482944 but that didn't really get conclusive. There was some a suggestion of using neither "or" nor "and", but applying this doesn't work consistently. This maybe works:

> Let activationTarget be target, if isActivationEvent is true and target has activation behavior, null otherwise.

This does not seem to work:

> To pop from a stack is to remove its last item and return it, if the stack is not empty, to return nothing otherwise.

cc @othermaciej @gsnedders @padenot

**Comment by othermaciej** [comment]
I'd write these two examples as:

> Let activationTarget be target if isActivationEvent is true and target has activation behavior, otherwise null.

> To pop from a stack is to remove its last item and return it if the stack is not empty, otherwise return nothing.

But the last one is not a good analogy for a ternary expression, because it has two imperative clauses so it's more like an if statement. The ternary construct doesn't apply because removing from the stack happens only on one branch. Thus:

> To pop from a stack: if the stack is not empty, remove the stack's last item and return it; otherwise return nothing.

**Comment by tjcrowder** [comment]
If you don't mind input from a bystander who benefits from your standards work (thank you!!):

FWIW, in your first example, you wouldn't normally use that first comma, so:

> Let activationTarget be target if isActivationEvent is true and target has activation behavior, null otherwise.

The second example (where it doesn't work) is a different kind of sentence, defining an operation rather than setting a value. Suggestion:

> To pop from a stack: If the stack is not empty, remove its last item and return it; otherwise, return nothing.

or if either part is particularly long and cumbersome, a pair of bullets:

> To pop from a stack:
> * If the stack is not empty, remove its last item and return it
> * Otherwise, return nothing

**Comment by sideshowbarker** [comment]
> FWIW, in your first example, you wouldn't normally use that first comma, so:
> 
> > Let activationTarget be target if isActivationEvent is true and target has activation behavior, null otherwise.

Yeah, that looks also reads best to me — although I think using a semicolon before *null* there (rather than a comma) would make it even better.

> The second example (where it doesn't work) is a different kind of sentence, defining an operation rather than setting a value. Suggestion:
> 
> > To pop from a stack: If the stack is not empty, remove its last item and return it; otherwise, return nothing.

Perfect.

> _(Edit: LOL, I see @othermaciej made virtually the same suggestion on the stack sentence while I was writing my comment. :-) )_

Yeah, and both with a semicolon…

**Comment by annevk** [comment]
Per discussion in #250 and https://github.com/whatwg/dom/pull/762 @domenic quite strongly prefers a variant where otherwise is preceded by ";" (or "or" or "and"). This would affect the first example:

> Let activationTarget be target if isActivationEvent is true and target has activation behavior; otherwise null.

(There's also some variation as to whether "null" or "otherwise" comes first. It seems that "otherwise" first reads better.)

Here's another example in this style we discussed:

> Let nodes be node's children, if node is a DocumentFragment node; otherwise « node ».

I hope this outcome is agreeable. I'll update the various PRs assuming it is.
