### ISSUE TITLE
Incorrect algorithm for byte sequence starts with and string code unit prefix

### ISSUE THREAD

**Issue by al-arz** [whatwg/infra#256]
Byte sequence **starts with** https://infra.spec.whatwg.org/#byte-sequence-starts-with has a step (2.3 "If aByte is null, then return true") that results in treating certain shorter sequences as starting with certain longer sequences, e.g. `abc` starting with `abcd`, while really it's vice versa.

String **code unit prefix** https://infra.spec.whatwg.org/#code-unit-prefix, being essentialy the same algorithm, has the same problem.

**Comment by annevk** [comment]
I saw on IRC you might be open to fixing this? If that's still the case and you can sign https://participate.whatwg.org/agreement that'd be great.

**Comment by al-arz** [comment]
> I saw on IRC you might be open to fixing this?

Absolutely. Just had a crunchy deadline at work this past weekeend. Ugh.

Now it's getting back to normal so I'm actually about to figure out what's the right procedure for contributing. Not a big deal, since all the info are out there (excellent work you've all done laying it out). And thanks for the tip!
