### ISSUE TITLE
Making abortable algorithms easier

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/infra#257]
Warning: half-baked idea ahead.

[Conditional abort](https://infra.spec.whatwg.org/#algorithm-conditional-abort) is great, although it's somewhat awkward in larger algorithms.

Imagine:

1. Let a be the result of starting machine A.
1. Let b be the result of starting machine B.
1. Increment global counter by 1.
1. Let c be the result of starting machine C.
1. Resolve promise.

You either end up with:

1. Let a be null.
1. Let b be null.
1. Let c be null.
1. Run these steps, but abort when the user clicks the "Cancel" button:
    1. Set a to the result of starting machine A.
1. If aborted, then:
    1. Stop a.
    1. Reject promise.
    1. Abort these steps.
1. Run these steps, but abort when the user clicks the "Cancel" button:
    1. Set b to the result of starting machine B.
1. If aborted, then:
    1. Stop a.
    1. Stop b.
    1. Reject promise.
    1. Abort these steps.
1. Run these steps, but abort when the user clicks the "Cancel" button:
    1. Increment global counter by 1.
1. If aborted, then:
    1. Stop a.
    1. Stop b.
    1. Decrement global counter by 1.
    1. Reject promise.
    1. Abort these steps.
1. Run these steps, but abort when the user clicks the "Cancel" button:
    1. Set c to the result of starting machine C.
1. If aborted, then:
    1. Stop a.
    1. Stop b.
    1. Stop c.
    1. Decrement global counter by 1.
    1. Reject promise.
    1. Abort these steps.
1. Resolve promise.

Or:

1. Let a be null.
1. Let b be null.
1. Let c be null.
1. Let incremented be false.
1. Run these steps, but abort when the user clicks the "Cancel" button:
    1. Set a to the result of starting machine A.
    1. Set b to the result of starting machine B.
    1. Set c to the result of starting machine C.
    1. Increment global counter by 1 and set incremented to true.
    1. Set c to the result of starting machine C.
1. If aborted, then:
    1. If a is not null, then stop a.
    1. If b is not null, then stop b.
    1. If c is not null, then stop c.
    1. If incremented is true, then decrement global counter by 1.
    1. Reject promise.
    1. Abort these steps.
1. Resolve promise.

Instead, could we assign a 'rollback' step to particular steps? Rollback steps would be processed in reverse order, from the point the algorithm reached when it was aborted.

1. Run these steps, but cancel if the user clicks the "Cancel" button:
    
    Cancel step: Reject promise.

    1. Let a be the result of starting machine A.

        Cancel step: Stop a.

    1. Let b be the result of starting machine B.

        Cancel step: Stop b.

    1. Increment global counter by 1.

        Cancel step: Decrement global counter by 1.

    1. Let c be the result of starting machine C.

        Cancel step: Stop c.

    1. Resolve promise.

**Comment by jakearchibald** [comment]
I've experimented with this idea: https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1443.html#aborting-algorithms.

It feels useful for algorithms that have steps that need to roll back when aborted. Or is it too confusing?

**Comment by annevk** [comment]
I think your seven-step variant is not that bad personally. Is there evidence of that being a common enough pattern to warrant further abstraction?

**Comment by jakearchibald** [comment]
I'm going to write it off as a bit of an experiment, and come back if I have a better idea.

I liked being able to 'throw' abort, so callers could also react to the algorithm aborting. I also liked that you could quickly identify a side-effect step with its related 'undo' step.

However, I think those things are achievable in other ways.
