### ISSUE TITLE
JSON serialization/deserialization to/from bytes doesn't handle undefined and 0 bytes

### ISSUE THREAD

**Issue by kenchris** [whatwg/infra#264]
![image](https://user-images.githubusercontent.com/1101339/63834387-83235c00-c975-11e9-8eca-ca213634cfe4.png)

`JSON.stringify` can return undefined if called with things like `undefined` or `Symbol('mySymbol')`

This should result in 0 bytes (null) being the result of the algorithm. We can of course also just make it return an error and handle it elsewhere

deserialization should probably also assert that there is actually a non-zero length byte sequence

**Comment by annevk** [comment]
Parsing should throw on the empty byte sequence, no? I'm not sure why we'd require a non-throwing input. We'd have to modify a bunch of callers if we'd decide to do that.

For serialization I'm not sure it makes sense to return the empty byte sequence, as that's not valid JSON. I'd be somewhat inclined to throw as well, though not entirely sure what exception.

**Comment by kenchris** [comment]
So JSONparse has this

![image](https://user-images.githubusercontent.com/1101339/63836482-ec0cd300-c979-11e9-8326-87316b69da37.png)

But not sure what toString would be called with when there is an empty byte sequence? (null or undefined?)

![image](https://user-images.githubusercontent.com/1101339/63836558-11014600-c97a-11e9-959e-064c23c75eb5.png)

> I'd be somewhat inclined to throw as well, though not entirely sure what exception.

SyntaxError seems consistent with the above

**Comment by annevk** [comment]
@kenchris _jsonText_ is not a byte sequence, we pass that function a string.

**Comment by kenchris** [comment]
Right, we just need to handle 0 bytes ourselves, as UTF8Encode of 0 bytes makes no sense.

**Comment by annevk** [comment]
I'm not sure I understand, the parser decodes and decoding the empty byte sequence works fine.

**Comment by kenchris** [comment]
OK, what does it decode it to? @zolkis and I found it hard following the algorithms in the encoding spec

**Comment by annevk** [comment]
To an empty code point stream, which can be coerced automatically into a string.

**Comment by andreubotella** [comment]
Looking at this, it seems like there's still an issue with the call to `%JSONStringify%` being able to return `undefined`. Presumably the operation should throw in that case, so any result of serialization can round-trip.

Additionally, there should probably be a note indicating that those operations can throw, and that serialize can execute user code and cause side effects.

**Comment by domenic** [comment]
Round-tripping is not necessarily a goal. And undefined is a valid stringification, if you pass it undefined.

**Comment by andreubotella** [comment]
`undefined` may be a valid stringification in Javascript land, but here Infra proceeds to UTF-8 encode it, which is not valid. And I wasn't talking so much about round-tripping of Infra values as that the output of serialization doesn't throw when deserialized.
