### ISSUE TITLE
Code unit prefix uses the wrong string length

### ISSUE THREAD

**Issue by andreubotella** [whatwg/infra#288]
For the longest time I was under the impression that the definitions of length for Javascript strings and for (not explicitly Javascript) strings were equivalent. The difference is easy to miss when skimming through the spec, but what makes it clear that the definition can be confusing is that the code unit prefix algorithm just below uses the wrong kind of length:

> Let `aCodeUnit` be the `i`th [code unit](https://infra.spec.whatwg.org/#code-unit) of `a` if `i` is less than `a`’s [length](https://infra.spec.whatwg.org/#string-length); otherwise null.

"Length" there links to the definition of a (not explicitly Javascript) string's length, which measures code points, not code units. Aside from changing the link, the text would also need to be updated, though I'm not sure if something like "`a`'s length as a Javascript string" would be the way to do it.

I'd also ask for a note clarifying the difference between the lengths, but that can be its own separate issue if need be.

**Comment by annevk** [comment]
Nice find! (It's not an issue for forgiving-base64 because it fails for non-ASCII inputs.)

I think updating the link is enough though maybe we should make it explicit that "code unit prefix" takes two JavaScript strings by including those in the "header".

(An alternative might be to use a different term, but that would be a larger effort as it affects downstream usage which we'd have to find and patch.)

**Comment by andreubotella** [comment]
The distinction between Javascript strings and simply "strings" is subtle, and simply "string" being an ambiguous term doesn't help. "`a`'s length as a Javascript string" feels far more clear to me than giving the types as Javascript strings in the header, but my mental model is that of a single `DOMString`/`Vec<u16>` type with both a code unit length and a code point length. Someone with the mental model of, say, "string" as a composite type of Javascript string and USV string might prefer having "Javascript string" as the type in the header.

I'll be working on the pull request as well. Should I add a clarifying note for string's length as well, or is that a separate concern and it'd need a separate PR?

**Comment by annevk** [comment]
I'd support adding the note, but I rather not require inline annotation on usage. If you think the usage sites need to be clearer, we should look into renaming the term and adjusting all callers.

**Comment by andreubotella** [comment]
Adding the note on usage seemed like the path of less resistance, but I see what you mean.
