### ISSUE TITLE
Clean up strings and string lengths

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#291]
As discussed in #289 the current setup can be confusing. This is what I think we should do:

> I think I prefer equating string and JavaScript string, defining scalar value string and ASCII string as subsets, and then have code unit length and code point length. One of code unit length or code point length should also be called length, but which would really depend on usage.

A reasonable start might be to do the above and keep both lengths we have today around as aliases for code unit length and code point length until we know which one to deprecate and remove. (Or perhaps we should favor neither and try to remove both shorthands.)

cc @andreubotella

**Comment by andreubotella** [comment]
I've been looking through the standards listed in the wiki as dependent on Infra, to inform how this issue proceeds and where changes are needed. Though we should also do some reasonable effort to check the usages on dependent specs that aren't listed in the wiki.

In general, specifications use the term "string" a lot, usually not bothering to reference Infra (and when they do it's once or twice in the whole spec). But "JavaScript string" is more rare. Below I'm listing all cases where "JavaScript string" is used, as well as any usages of either "length". Dependent specs I'm not listing aren't affected:

HTML:
- Beside the many times that HTML uses "string" without linking back to Infra, it also uses "JavaScript string" ([1](https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute:javascript-string), [2](https://html.spec.whatwg.org/multipage/webappapis.html#creating-scripts:javascript-string), [3](https://html.spec.whatwg.org/multipage/webappapis.html#creating-scripts:javascript-string-2), [4](https://html.spec.whatwg.org/multipage/webappapis.html#integration-with-the-javascript-module-system:javascript-string), [5](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-for-spec-authors:javascript-string), [6](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-for-spec-authors:javascript-string-2), [7](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-for-spec-authors:javascript-string-3)). There doesn't seem to be a pattern to the usage of one term over the other.
- HTML uses both "JavaScript string length" ([1](https://html.spec.whatwg.org/multipage/input.html#the-maxlength-and-minlength-attributes:javascript-string-length), [2](https://html.spec.whatwg.org/multipage/form-elements.html#the-textarea-element:javascript-string-length), [3](https://html.spec.whatwg.org/multipage/form-elements.html#the-textarea-element:javascript-string-length-2), [4](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#limiting-user-input-length:-the-maxlength-attribute:javascript-string-length), [5](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#limiting-user-input-length:-the-maxlength-attribute:javascript-string-length-2), [6](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#limiting-user-input-length:-the-maxlength-attribute:javascript-string-length-3), [7](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#setting-minimum-input-length-requirements:-the-minlength-attribute:javascript-string-length), [8](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#setting-minimum-input-length-requirements:-the-minlength-attribute:javascript-string-length-2)), and "length" meaning string length ([1](https://html.spec.whatwg.org/multipage/microdata.html#conversion-to-vcard:string-length), [2](https://html.spec.whatwg.org/multipage/microdata.html#conversion-to-icalendar:string-length)).
- The [6.8 Drag and drop](https://html.spec.whatwg.org/multipage/dnd.html) section uses the terms "Unicode string" (also referred to as "Plain Unicode string" and "text") and "binary string" (also "file") to distinguish between binary and textual data exposed by the API. They should probably be replaced with the standard Infra terms "string" and "byte sequence". Similarly, the two notes to the [8.3 Base64 utility methods](https://html.spec.whatwg.org/multipage/webappapis.html#atob) section also use "Unicode string" for no apparent reason, and the definition for [XML parser](https://html.spec.whatwg.org/multipage/xhtml.html#xml-parser) talks about mapping "a string of bytes or characters" into a Document object.
- There are a few algorithms or definitions that use "length" applied to strings ambiguously and without referencing Infra:
  - A definition for "empty" string (or DOM node containing just a string) in section [2.1.4 DOM trees](https://html.spec.whatwg.org/multipage/infrastructure.html#dom-trees) that isn't referenced from anywhere.
  - The [prefix match](https://html.spec.whatwg.org/multipage/infrastructure.html#prefix-match) algorithm (if defined in terms of code units, this algorithm would become equivalent to Infra's [code unit prefix](https://infra.spec.whatwg.org/#code-unit-prefix)).
  - The [rules for parsing a legacy color value](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#rules-for-parsing-a-legacy-colour-value) uses "length" without referencing Infra, but at that point in the algorithm `input` can only have characters in the BMP.
  - A number of algorithms and APIs in section [4.10.19 APIs for the text control selections](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#textFieldSelection) use lengths and offsets ambiguously. All three major browser engines seem to implement them as referring to the code unit representation.
  - The index summarizes the `minlength` and `maxlength` attributes as "minimum/maximum length of value", although the normative definition is in terms of the Javascript string length.

DOM:
- It uses "length" linking to "JavaScript string length" ([1](https://dom.spec.whatwg.org/#ref-for-javascript-string-length), [2](https://dom.spec.whatwg.org/#ref-for-javascript-string-length%E2%91%A0), [3](https://dom.spec.whatwg.org/#ref-for-javascript-string-length%E2%91%A1), [4](https://dom.spec.whatwg.org/#ref-for-javascript-string-length%E2%91%A2)).

Encoding:
- [A note](ref-for-javascript-string-convert) refers to Infra's [convert a JavaScript string into a scalar value string](https://infra.spec.whatwg.org/#javascript-string-convert) algorithm, also linking to the definition of JavaScript string. The note should be changed with the rename of the algorithm.

URL:
- It uses "length" linking to "string length" ([1](https://url.spec.whatwg.org/#ref-for-string-length), [2](https://url.spec.whatwg.org/#ref-for-string-length%E2%91%A0)).

WebDriver:
- It uses "JavaScript string's length" once.
- At [one point](https://w3c.github.io/webdriver/#dfn-user-prompt-message) it checks whether a "message length" is 0. Although I'm not familiar with this spec, it seems to be a string length, in which case it should probably be replaced with something like "if the message is the empty string".

Bonus feature unlocked – WebIDL:
- Although WebIDL's concept of strings comes from the ECMAScript spec, it uses the term "JavaScript string" [once](https://heycam.github.io/webidl/#ref-for-javascript-string).

**Comment by annevk** [comment]
URL's usage seems fine if it changes to code unit length so I'm going to leave that as-is. Created PRs/issues for the remainder.

**Comment by annevk** [comment]
I'm going to consider this done. Thanks again @andreubotella (and @domenic!) for finding this and helping resolve it.
