### ISSUE TITLE
Byte sequences are "byte less than" their prefixes

### ISSUE THREAD

**Issue by gabpiv** [whatwg/infra#309]
Hi,

I noticed that the [byte less than](https://infra.spec.whatwg.org/#byte-less-than) operation on byte sequences produces unexpected results if one of the byte sequences [starts with](https://infra.spec.whatwg.org/#byte-sequence-starts-with) the other one (i.e. it has the other one as a prefix). For example, consider the byte sequences

_A_ = `` `Hello world` ``,
_B_ = `` `Hello` ``.

In determining whether or not _A_ is byte less than _B_, the algorithm proceeds as follows:

1. _B_ **does not** start with _A_, so move on to step 2.
2. _A_ **does** start with _B_ (`` `Hello world` `` starts with `` `Hello` ``), so return true.

This means that _A_ is byte less than _B_, or `` `Hello world` `` is byte less than `` `Hello` ``. This ordering is not consistent with the analogous ordering on code units, [code unit less than](https://infra.spec.whatwg.org/#code-unit-less-than). If we consider the corresponding strings

_sA_ = `"Hello world"`,
_sB_ = `"Hello"`,

we can see that _sB_ is a code unit prefix of _sA_, so _sA_ is **not** code unit less than _sB_ according to [the "code unit less than" algorithm](https://infra.spec.whatwg.org/#code-unit-less-than).

It seems to me that in [the "byte less than" algorithm](https://infra.spec.whatwg.org/#byte-less-than), the variables _a_ and _b_ should be swapped in step 1 and step 2. This would cause the algorithm to return false if _b_ is a "byte prefix" of _a_ (meaning that _a_ starts with _b_) and return true if _a_ is a "byte prefix" of _b_.

**Comment by domenic** [comment]
Sigh. We've really messed up these algorithms. Thank you for finding this. See previous fixes in https://github.com/whatwg/infra/commit/cdd49653c2ae11d09391869c8a241046d414143c. Thank you for spotting this!
