### ISSUE TITLE
Serialize Infra values to JSON bytes

### ISSUE THREAD

**Issue by foolip** [whatwg/infra#336]
We have https://infra.spec.whatwg.org/#serialize-json-to-bytes which takes JS values, but nothing that takes Infra values. This would be convenient in https://w3c.github.io/webdriver-bidi/, where we use Infra sets, and then want to serialize those and send as a WebSocket message.

**Comment by domenic** [comment]
I'll take a stab at this. The necessary ECMA-ese of assembling an object will be nontrivial.
