### ISSUE TITLE
Encourage "gerund" definitions for algorithms that return values

### ISSUE THREAD

**Issue by jyasskin** [whatwg/infra#337]
https://infra.spec.whatwg.org/#algorithm-declaration currently encourages algorithm definitions of the form

> To [infinitive], given [parameters], perform the following steps. They return a [return type].

However, call sites need to capture that return value, so they wind up looking like

> Let [var] be the result of [gerunding], given [parameters].

In Bikeshed, that means the definition winds up looking like

```html
To <dfn lt="infinitive|gerunding">infinitive</dfn> ...
```

Or authors forget to include the `lt`, which forces callers to add it to every call site. https://github.com/whatwg/streams/pull/1079 has an example of fixing this forgetfulness.

Algorithm authors should instead write something like

> [Gerunding], given [parameters], consists of the following steps, which return a [return type]:

This makes the call site look more like the definition and avoids the need for extra markup.

**Comment by tabatkins** [comment]
I just fixed the common case here, where the modified word is the first in a phrase (rather than the last, which already works), so this shouldn't be necessary any longer, and just dfn'ing the infinitive form should work fine.

**Comment by tabatkins** [comment]
Should we close this? Most algorithms (any with reasonably regular infinitive->gerunding conversion) are handled by Bikeshed now. Maybe we want some guidance on adding the gerund form when it's irregular? Or maybe just "consider these X common ways algorithms are invoked, and make sure you're not horribly awkward in any of them; tooling can solve some of these automatically"?

**Comment by annevk** [comment]
I think it's fair to close this. If there were to be any documentation about this it's probably better suited for Bikeshed. Infra sits at a slightly higher level that does not have to worry about how things get linked.
