### ISSUE TITLE
Permanent anchor for tracking-vector

### ISSUE THREAD

**Issue by martinthomson** [whatwg/infra#349]
As per https://whatwg.org/working-mode#anchors could https://infra.spec.whatwg.org/#tracking-vector be made a permanent anchor?

This will be cited in the upcoming revision to RFC 7540, where it will replace a reference to "fingerprinting" since removed from the HTML spec.

**Comment by domenic** [comment]
For sure, consider it permanent! I'll send a PR to make our tooling enforce that, which will close this issue when it's merged.
