### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by sri-ka1ki** [whatwg/infra#354]
https://infra.spec.whatwg.org/commit-snapshots/9b412bce81d3d1b120cc671210599328cdcd764c/

When I access these type of docs they are colored as if already selected.

**Comment by annevk** [comment]
Could you elaborate a bit, perhaps include a screenshot?

**Comment by sri-ka1ki** [comment]
[
![Screenshot_20210119-170531_Firefox Nightly](https://user-images.githubusercontent.com/72894943/105112870-b0940c80-5a78-11eb-8161-5a625e866a7c.jpg)
](url)

**Comment by sri-ka1ki** [comment]
This and many other probs 😕

**Comment by annevk** [comment]
Is the problem the overlapping text on smaller screens?

**Comment by domenic** [comment]
You can scroll down a bit further to see any text underneath the "File an issue about the selected text", if that's what you're discussing. But I'm not sure; the original issue is about colors...

**Comment by sri-ka1ki** [comment]
My apologies, that was a reference to the little tag that says to file an issue. So sorry about the confusion. There no longer seems to be an issue. What I was referring to was a symptom of another technical issue. Thank you for you response. I really appreciate you
