### ISSUE TITLE
Provide a way to iterate/get values of a map

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/infra#36]
Bikeshed complains if a variable is unused, which happens if you iterate over a map but don't use the key.

The can be worked around with `<var ignore>`, but maybe it's better to have an explicit way to handle just values? There's already a way to get just the keys.

**Comment by domenic** [comment]
Sounds reasonable. Out of curiousity, how does this show up in a spec?

I guess the alternative is "For each _var_ in _map_, use _map_[_var_]" (or add a step aliasing _map_[_var_]).

**Comment by jakearchibald** [comment]
> Out of curiousity, how does this show up in a spec?

It doesn't change the output, but in bikeshed's error log it says something like "Variable 'key' only used once in this algorithm - probably a typo"

**Comment by domenic** [comment]
No, I meant, in what kind of scenario does a spec need to iterate over a map and only use the values?

**Comment by jakearchibald** [comment]
Ahh gotcha. Service worker caches are mapped to cache names, so I'm using an ordered map. But when it comes to `caches.match()` it's implementation is roughly:

```js
for await (const cache of caches) {
  const response = caches.match(request);
  if (response) return response;
}
return undefined;
```

In this case the keys aren't needed.

**Comment by annevk** [comment]
Should it be cache.match in that snippet? Otherwise you might as well do caches.match(request) without the loop, right?

**Comment by jakearchibald** [comment]
@annevk yes, sorry, updated.

**Comment by annevk** [comment]
Would it work if we added "get the values" which returns a list and then you can iterate over that? We already have "get the keys", adding "get the values" seems good.

**Comment by jakearchibald** [comment]
Yes, that's exactly what I'm looking for.

**Comment by annevk** [comment]
I see now the title of this issue suggests exactly that. Oops! Created a PR.
