### ISSUE TITLE
Provide guidance on usage of maps

### ISSUE THREAD

**Issue by gsnedders** [whatwg/infra#373]
e.g., when should one use "convert a JSON-derived JavaScript value to an Infra value" v. just using the JSON-derived JavaScript value directly?

**Comment by domenic** [comment]
https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-for-spec-authors is relevant here.

In general, you can use the JSON-derived JavaScript values if you have a JS engine available and are prepared to handle all the wackiness of JS properties yourself. (Although that wackiness is somewhat constrained for JS-produced objects, it isn't fully, e.g. you can still accidentally trigger getters on the prototype if you don't use exactly the right incantations.)

**Comment by domenic** [comment]
In my mind the existing spec text

> The above operations operate on JavaScript values directly; in particular, this means that the involved objects or arrays are tied to a particular JavaScript realm. In standards, it is often more convenient to convert between JSON and realm-independent maps, lists, strings, booleans, numbers, and nulls. 

tries to answer this, so I'd love to hear more on what specifically you're looking for.

**Comment by domfarolino** [comment]
I kind of feel like this can be closed given the above comment and inactivity here. @domenic do you agree / should we just close this?
