### ISSUE TITLE
Term to reference internal concepts

### ISSUE THREAD

**Issue by jungkees** [whatwg/infra#40]
For discussion, we tend to call definitions of spec concepts a _concept_ and their fields an _internal slot_ which is an ECMAScript's specification device. Can we clarify terminologies to reference these internal spec definitions?

**Comment by annevk** [comment]
I think that makes sense. I think part of this is something that needs to be handled by IDL, when we're talking about internal slots of JavaScript/IDL object instances. But maybe part of it can be handled here.

**Comment by tobie** [comment]
Agreed, slots belong in WebIDL, maybe concepts belong here?

**Comment by annevk** [comment]
So for concepts I had this idea of record-like structures, see #13. No feedback on it thus far unfortunately. (Sorry for the delay in replies, I should go through Infra backlog more often.)

**Comment by annevk** [comment]
I forgot to close this in 139484a9b0fddfc3a6ad48e13cb330ce4c44babe. We now call these structs.
