### ISSUE TITLE
Change link re "for lists"

### ISSUE THREAD

**Issue by jmdyck** [whatwg/infra#406]
https://github.com/whatwg/infra/blob/93235624046ab39b2dd880d4091447cc8d0b84d5/infra.bs#L521

The link-text makes it look like there are things called "for lists". I suggest moving the "for" outside the link:

```<dd><p>As defined for <a for=list lt="for each">lists</a> (and derivatives) and ...```

**Comment by domenic** [comment]
This is the first time I've seen someone be confused by this style of hyperlinking, but your suggested modification seems not that much worse, so PRs welcome.

**Comment by jmdyck** [comment]
Heavens no, I wouldn't want to make things worse.
