### ISSUE TITLE
Use of "one of"

### ISSUE THREAD

**Issue by jungkees** [whatwg/infra#41]
When referencing one of the items from a list, is using "and" or "or" more accurate one over the other? Or they don't matter much? Both of them are being used.

> One of "uninstantiated", "errored", or "instantiated", used to prevent reinvocation of ModuleDeclarationInstantiation on modules that failed to instantiate previously.

> If header list contains a header whose name is one of `If-Modified-Since`, `If-None-Match`, `If-Unmodified-Since`, `If-Match`, and `If-Range`, ...

> If origin’s host component matches one of the CIDR notations 127.0.0.0/8 or ::1/128

> A job is an abstraction of one of register, update, and unregister request for a service worker registration.

**Comment by zcorpan** [comment]
Intuitively I think "and" is more appropriate when saying "one of". It's one item of a set, and a set is "foo, bar, and baz", not "foo, bar, or baz"...

**Comment by domenic** [comment]
Based on vague feeling of English flow, "or" seems more correct, but I can't find any sources, and @zcorpan's explanation is more logical. https://english.stackexchange.com/questions/149415/maybe-one-of-a-or-c-cheated-is-this-correct is the best I've got.

I think this is more in the realm of English grammar than spec infrastructure, so probably we won't have anything actionable to do here on the spec, but happy to leave open in the hopes of getting some more discussion...

**Comment by annevk** [comment]
I started avoiding "one of" unless it's followed by a bulleted list. You can normally leave it out and just use "or". If you cannot leave it out, that might be a good indication you want to use a bulleted list for clarity.

**Comment by jungkees** [comment]
> "and" is more appropriate when saying "one of". It's one item of a set

> feeling of English flow, "or" seems more correct

Exactly which I've been between.  I don't think using any of them will be an issue unless it goes unclear in a given context.

FYI. I just looked what ECMAScript spec does:

> If symbol is not one of NewTarget, SuperProperty, SuperCall, super or this, return false.

> Any Promise object is in one of three mutually exclusive states: fulfilled, rejected, and pending: fulfilled, rejected, and pending:

> The abstract operation FunctionInitialize requires the arguments: a function object F, kind which is one of (Normal, Method, Arrow), ..

I also think @annevk's suggestion to use a bulleted point wherever needed for clarity is a good idea.

Feel free to close this.

**Comment by sideshowbarker** [comment]
> I started avoiding "one of" unless it's followed by a bulleted list. You can normally leave it out and just use "or". If you cannot leave it out, that might be a good indication you want to use a bulleted list for clarity.

Added to https://wiki.whatwg.org/wiki/Style
