### ISSUE TITLE
Add "context object"

### ISSUE THREAD

**Issue by zcorpan** [whatwg/infra#42]
I think we should move https://dom.spec.whatwg.org/#context-object to Infra. But consider renaming it at the same time, as has been suggested somewhere, "this" is probably less confusing than "context". HTML uses "this element" etc (without cross-referencing) in some places.

**Comment by domenic** [comment]
I think this might belong in Web IDL instead. My rule of thumb is that Infra stuff should be generally be applicable to non-IDL specs or even non-web specs.

**Comment by annevk** [comment]
IDL issue is https://www.w3.org/Bugs/Public/show_bug.cgi?id=27301. I tend to agree with formalizing it there.
