### ISSUE TITLE
Add VoidFunction

### ISSUE THREAD

**Issue by tabatkins** [whatwg/infra#46]
Several specs end up needing to define IDL that accepts a function which is called for its side effects, which means they use something like:

```
callback VoidFunction = void ();
```

It would be nice to have this defined in Infra so we didn't have to worry about colliding global names for this trivial concept.

**Comment by tabatkins** [comment]
(Relevant issue: https://github.com/w3c/css-houdini-drafts/issues/335)

**Comment by domenic** [comment]
So in general I think Infra is supposed to be below the layer of stuff like Web IDL. So we could add this to Web IDL instead. Maybe we should mention that in the goals section.

(Although it's not clear what would be gained over using the existing `Function` type.)

**Comment by foolip** [comment]
https://heycam.github.io/webidl/#common already has VoidFunction.

**Comment by annevk** [comment]
Thanks @foolip!
