### ISSUE TITLE
"An ASCII lower alpha is a code point in the ran..."

### ISSUE THREAD

**Issue by xfq** [whatwg/infra#50]
https://infra.spec.whatwg.org/commit-snapshots/208e4e04632d0c8514a8b5f26f99c8472d7e836d/#example-code-point-notation

> An ASCII lower alpha
> is a code point in the range U\+0041 to U\+005A, inclusive\.
> 
> An ASCII upper alpha
> is a code point in the range U\+0061 to U\+007A, inclusive\. 

* U+0041 is Latin Capital Letter A
* U+005A is Latin Capital Letter Z
* U+0061 is Latin Small Letter a
* U+007A is Latin Small Letter z

So the first range should be ASCII upper alpha; the second range should be ASCII lower alpha.

**Comment by annevk** [comment]
Oops, thanks! How would you like to be acknowledged?

**Comment by xfq** [comment]
I'll submit a pull request later (not for this issue) and add myself to the Ack section.

I can also submit a PR for this issue, if you think it's needed.

**Comment by annevk** [comment]
If you want, that'd be great. We generally run everything through PRs just in case.

**Comment by xfq** [comment]
Done. See #51 and #52.
