### ISSUE TITLE
empty string isn't defined

### ISSUE THREAD

**Issue by icecream17** [whatwg/infra#504]
Well, https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-language-types-string-type does define empty string, and it is pretty obvious, but Infra itself doesn't have a link for empty string.

(Unless strings are considered as lists somehow. (I don't think they are, even though strings are finite ordered sequences.))

(Edit: "empty list" is defined by "list is empty", though it doesn't automatically link)

**Comment by domenic** [comment]
What do you find ambiguous about the English language term, such that you need an Infra definition to link to? Could you give two examples definitions you find equally plausible, so we can help craft one that dispells your confusion?

**Comment by icecream17** [comment]
there's nothing ambiguous
