### ISSUE TITLE
Define ordering for sets and maps?

### ISSUE THREAD

**Issue by domfarolino** [whatwg/infra#617]
I am reviewing [a PR](https://github.com/WICG/turtledove/pull/771) which uses an infra map whose keys are structs. If one were to enumerate the map and print all values, in what order should the map entries be iterated over? A "struct" isn't a primitive, so it doesn't have any obvious default comparison operators. Should we make people provide their own? Or should map keys not be allowed to be structs, and instead be restricted to [primitive types](https://infra.spec.whatwg.org/#primitive-data-types)? Even if we did the latter, we'd still have to deal with ordered sets, which are just lists with ["items"](https://infra.spec.whatwg.org/#list-item), and we certainly can't restrict _all_ "items" to primitives. (Maybe we could just for _ordered set_ items?).

**Comment by annevk** [comment]
I'm not sure I understand the problem. A map is by definition ordered: https://infra.spec.whatwg.org/#ordered-map.

**Comment by domfarolino** [comment]
I'm not saying we should define the fact that maps are "ordered" (we already do that). I'm asking if we should define how that ordering is determined. At least my assumption is that the "ordered" data structures rely on some sort of sorting to achieve that ordering. If you have an ordered set of Fetch _request_ objects, and you iterate over the entire set, then in what order do you iterate over them? How do we "sort" the request objects? By ID? By URL? To be truly ordered a lot of languages would require you to pass in a custom comparator when one is not obvious from the input type.

**Comment by annevk** [comment]
There is no sorting. The order is defined through insertion.

**Comment by domfarolino** [comment]
I see, I guess I'm now realizing that's how JS's `Set` works too, etc. I guess I had `std::map` and `std::unordered_map` stuck in my brain when filing.
