### ISSUE TITLE
byte sequence backtick representation handling of C0 controls

### ISSUE THREAD

**Issue by aphillips** [whatwg/infra#63]
https://infra.spec.whatwg.org/#byte-sequences

In this section is the text:

> Byte sequences with bytes in the range 0x00 to 0x7F, inclusive, can alternately be written as a string, but using backticks instead of quotation marks, to avoid confusion with an actual string. 

This is intended for showing ASCII byte sequences as strings, but ignores that control characters such as NUL, escape, newline, etc. are not printable or would mess up the display (or show as tofu boxes and cannot be discerned). I'd suggest making the range go from 0x20 to 0x7F instead.

Is the backtick byte sequence representation really that useful anyway?

**Comment by annevk** [comment]
We use the representation a lot in Fetch for HTTP-related things. Restricting it to >0x19 should be fine however.
