### ISSUE TITLE
Give some examples of how to use structs

### ISSUE THREAD

**Issue by jyasskin** [whatwg/infra#633]
### What problem are you trying to solve?

Some early iterations of https://github.com/w3c/vc-data-integrity/pull/244 included text like "An algorithm that takes proof options (struct options) as input and produces a proof configuration (struct proofConfig) as output". I believe Infra intends "struct" to be used to build concrete types, rather than be used directly as the type of a variable. But the current wording is ambiguous between that interpretation, and an interpretation of structs as another kind of map.

**Comment by Disastrous-young-411** [comment]
Feature
