### ISSUE TITLE
Operation to map/transform lists

### ISSUE THREAD

**Issue by jyasskin** [whatwg/infra#64]
I frequently want to build a new list based on an old one by modifying the old list's elements using substeps. Perhaps:

> 1. Let *newList* be the result of **transforming** each *item* of *oldList* through the following steps:
>    1. **Return** *item* + 2.

as shorthand for:

> 1. Let *newList* be a new **list**.
> 1. **For each** *item* of *oldList*:
>    1. **Append** *item* + 2 to *newList*.

"Return" could be "include" or "append" or some other term.

The text I'm proposing isn't much shorter, but it keeps the logical operation in a single step instead of spreading it across 2.

**Comment by domenic** [comment]
This seems like a good idea, although we probably shouldn't reuse "return" in this way. "Append" might work well.

**Comment by annevk** [comment]
I would be okay with this, but I think using two separate steps is just as clear, if not clearer (to me).

**Comment by annevk** [comment]
Any objection to closing this? Or has this come up more often?

**Comment by jyasskin** [comment]
It hasn't come up much since then for me.
