### ISSUE TITLE
Define ranged integer types

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#647]
Although tackling #87 is a pretty big endeavor, I wonder if we can start smaller, by defining things such as:

- A **16-bit unsigned integer** is an integer in the range 0 to 65535, inclusive.

This could be shared across Web IDL, URL, and Declarative Web Push. And probably other specifications.

**Comment by domenic** [comment]
This seems reasonable to me. Maybe with an XXX box pointing to the problems of https://github.com/whatwg/infra/issues/87, like how we haven't defined mathematical operations on 16-bit unsigned integers...
