### ISSUE TITLE
Which WebIDL types are maps?

### ISSUE THREAD

**Issue by jyasskin** [whatwg/infra#65]
Like #14, but plausible WebIDL maps include at least dictionaries, objects, and records. I care in order to [iterate](https://infra.spec.whatwg.org/#map-iterate) over them.

**Comment by domenic** [comment]
I'll try to tackle this and #14 within the next day or so, along the lines of the strategy of

> Maybe what we want to do here is state something like "often we use lists in a place that expects sequences, or treat sequences like lists. This kind of implicit conversion is OK, as long as the type systems match up."

However, as noted in #61, I think probably such Web IDL-specific stuff should get moved into Web IDL.

**Comment by jyasskin** [comment]
We may want to explicitly disallow objects, because of the ambiguities around own vs inherited properties. Dictionaries and records have unambiguous contents and ordering.

**Comment by domenic** [comment]
Closed by https://github.com/heycam/webidl/commit/26aa8308811da812d28a5b3dd06fabcefecb71f0 (I got the commit message wrong)
