### ISSUE TITLE
While true / loop until break

### ISSUE THREAD

**Issue by foolip** [whatwg/infra#66]
See https://github.com/whatwg/fullscreen/pull/72/files#r101013520 for a need for this.

Do we have cases like this in other specs, and what do they say?

**Comment by zcorpan** [comment]
http://w3c.github.io/webvtt/#collect-a-webvtt-block

> *Loop*: Run these substeps in a loop:

> ... break out of *loop*

**Comment by zcorpan** [comment]
"While true:" SGTM. Infra uses "While &lt;condition>:" in its algorithms, and it seems straightforward to say true for the condition.

Labels for loops, and being able to break out of a specific one with nested loops, is also necessary...

**Comment by foolip** [comment]
With "While true:", how would one break the loop? Just "break"?

**Comment by zcorpan** [comment]
Yeah.

**Comment by zcorpan** [comment]
Related: https://github.com/whatwg/infra/issues/56

**Comment by foolip** [comment]
https://fullscreen.spec.whatwg.org/#collect-documents-to-unfullscreen now uses this.
