### ISSUE TITLE
Define pairs

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#81]
In #79 @mikewest brought up pairs. I think we should consider defining them as a special case of tuples (fixed size of two) with their own / syntax.

I also think the `<dfn>` convention he mentions there is expected, but I'm not sure how to put `<dfn>` conventions into prose.

**Comment by annevk** [comment]
(It's also not clear to me if Infra should dictate `<dfn>` conventions.)

**Comment by domenic** [comment]
I think `<dfn>` conventions can be illustrated with examples.
