### ISSUE TITLE
Define character as alias of code point or stop using it

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#85]
We're currently using the term character to define syntax. We should probably stop doing that and use the syntax we outline for code points. Slightly weird to be informal here while we require much more of others.

See also #6 on the topic of whether or not to stop using character altogether as something that means code point all or some of the time (it seems somewhat silly to make it mean code point for something where Unicode says the code point is a non-character, but not out of the question).

**Comment by domenic** [comment]
You mean when we say

> by surrounding the list contents by « » characters

?

I guess that makes sense. In general I prefer the English names (as I proposed in my editorial change in #79) but for things without a common name like « » ("angled quotation marks"??) using the character directly is better.

**Comment by aphillips** [comment]
I think that for general consumption use of the term "character", it's useful to define it as a synonym for "code point" (where code point includes the non-character code points): it makes specs legible. I agree that one could be strict and say "code point" or "scalar value", but @domenic's example just above is a good one. It's clear what `character` means there without being pedantic.

Generally the problems emerge when people use the term "character" to mean "grapheme cluster" or "glyph" or (going the other direction) "byte". And when discussing specific mechanics of working with text I would tend to want to be clear about code unit, code point, etc. But to provide a definition as a synonym would be helpful for cases like the above where no one is in doubt.
