### ISSUE TITLE
Define initializing variables and setting them?

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#88]
I.e., let and set. We could do that with `<dfn>`, but I don't think we want to require documents to link instances.

**Comment by annevk** [comment]
(Additional question here is whether the type of a variable is allowed to change. I'd say no...)

**Comment by domenic** [comment]
This seems trivial but people seem to really appreciate guidance here. See e.g. https://garykac.github.io/procspec/ "local variables" section.

Agreed we can get away with no `<dfn>` here, similar to our current "return"/"throw".

One thing to also give clarity on is the "scope" of definitions. E.g. we've been trying to avoid declaring variables with "let" inside of "if" blocks.

I think the type of a variable isn't something we should touch, or at least we shouldn't go beyond a "should" recommendation. Specs are not strongly-typed enough for any recommendation here to make general sense.

**Comment by tobie** [comment]
Yeah, there's lots of disagreement here, see for example: https://github.com/heycam/webidl/pull/323#discussion_r103536749
