### ISSUE TITLE
Deal with list[n] access where n is negative or => size

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#90]
We should probably say that it's not possible or actually define what it would return. If we return something it would have to be value like "none" or some such, that doesn't mean anything else and needs to be explicitly dealt with.

**Comment by annevk** [comment]
(In my personal usage of list I've mostly been adding bound checks.)

**Comment by domenic** [comment]
Treating them as not possible is best IMO. I.e. it is a spec error to access out of bounds; you have to add bounds checks.

However we should I think allow text of the form "list[n] exists" similar to how we already allow "map[x] exists". Not sure it's as useful, but it's probably best to be symmetric.
