### ISSUE TITLE
Add basic JavaScript types

### ISSUE THREAD

**Issue by annevk** [whatwg/infra#95]
We should add undefined, null, and boolean (true, false). We haven't made much type-value distinction thus far so I'm not quite sure how to formulate this. Anyone ideas?

**Comment by annevk** [comment]
Split from #87.

**Comment by domenic** [comment]
I don't think we should have undefined in specs unless you are specifically dealing with JavaScript. And I think JavaScript should be a level above Infra.

I might just define the three values for now (inside the variables section?) without worrying about a type system.

**Comment by annevk** [comment]
It seems like it should be in "primitive data types", but maybe its own section called "primitive values"? Where would we define Number/BigInt?

**Comment by domenic** [comment]
Hmm yeah, primitive data types is probably better. Probably no need for a separate section. We'd definitely put number/bigint there.
